### ISSUE TITLE
ZigbeeMode

### ISSUE THREAD

**Issue by asg02fever** [sandzco/ESP32-EPD47-ToDoist-Display#1]
hey man i got a issue with your program only when i try to compile i got a error i never seen

Invalid FQBN: getting build properties for board esp32:esp32:esp32s3: invalid option 'ZigbeeMode'

Compilation error: Invalid FQBN: getting build properties for board esp32:esp32:esp32s3: invalid option 'ZigbeeMode'

**Comment by sKethired** [comment]
This project was implemented with the older version of T5 EPD47 that has 5 buttons on the top. The latest version has only 3 buttons. 

First try to get the Weather display to compile. If so, this projects should compile as well.

**Comment by sandzco** [comment]
This project was implemented with the older version of T5 EPD47 that has 5 buttons on the top. The latest version has only 3 buttons.

First try to get the Weather display to compile. If so, this projects should compile as well.

**Comment by asg02fever** [comment]
hey , i managed to compile it , i had to creat a new folder and copy all content of the ino and .h files to new one to remove the zigbee as u said its because of a older version the fil as been saved on , it is compiling and uplaoding correctly to the latest epaper t5 just one probleme is that when it try to get the http of the api it get into deepsleep even tho the ssid , pasw , api are correct
